app/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="base.html")),
]

social_message/urls.py
from django.contrib import admin
from django.urls import path, include
from app import urls as base_urls
from user_auth import urls as user_urls
from text_report import urls as report_urls

urlpatterns = [
    path('', include(base_urls), name='base'),
    path('admin/', admin.site.urls),
    path('auth/', include(user_urls)),
    path('report/', include(report_urls)),
]

text_report/urls.py
from django.urls import path
from .views import report_view, history_view, index_view

urlpatterns = [
    path('', index_view, name='index_view'),
    path('form/', report_view, name='text_report'),
    path('history/', history_view, name='history_view')
]

text_report/models.py
from django.db import models


# Create your models here.
class Report(models.Model):
    PLATFORMS = [
        ('1', 'hw-10-f1'),
        ('2', 'hw-100-n1'),
        ('3', 'hw-100-n2'),
        ('4', 'hw-100-n3'),
        ('5', 'hw-100-x3'),
        ('6', 'hw-100-x8'),
        ('7', 'hw-1000-q1'),
        ('8', 'hw-1000-q2'),
        ('9', 'hw-1000-q3'),
        ('10', 'hw-1000-q4'),
        ('11', 'hw-1000-q5'),
        ('12', 'hw-1000-q6'),
        ('13', 'hw-1000-q7'),
        ('14', 'hw-1000-q8'),
        ('15', 'hw-2000-q2'),
        ('16', 'hw-2000-q3'),
        ('17', 'hw-2000-q4'),
        ('18', 'hw-50-n1'),
        ('19', 'hw-50-n2'),
        ('20', 'hw-50-n3'),
        ('21', 'hw-50-n4'),
        ('22', 'va-10'),
        ('23', 'va-100'),
        ('24', 'va-1000')
    ]

    BUG = [
        ('1', 'Дефект продукта'),
        ('2', 'Дефект автостенда'),
        ('3', 'Новый дефект'),
        ('4', 'Доработка автотеста'),
        ('5', 'Возможный дефект продукта'),
    ]

    name = models.CharField(max_length=60)
    url_report = models.URLField(blank=True, null=True)
    platform_name = models.CharField(
        max_length=20,
        choices=PLATFORMS,
        default='1'
    )
    build_number = models.IntegerField()
    bug = models.CharField(max_length=30, choices=BUG, default=1)
    floating_defect = models.BooleanField(default=False)
    id_tfs = models.IntegerField(default=1)
    problem = models.TextField()
    my_solution = models.TextField()
    date_create = models.DateField(auto_now_add=True)

text_report/forms.py
from .models import Report
from django import forms


class ReportForm(forms.Form):
    PLATFORMS = [
        ('1', 'hw-10-f1'),
        ('2', 'hw-100-n1'),
        ('3', 'hw-100-n2'),
        ('4', 'hw-100-n3'),
        ('5', 'hw-100-x3'),
        ('6', 'hw-100-x8'),
        ('7', 'hw-1000-q1'),
        ('8', 'hw-1000-q2'),
        ('9', 'hw-1000-q3'),
        ('10', 'hw-1000-q4'),
        ('11', 'hw-1000-q5'),
        ('12', 'hw-1000-q6'),
        ('13', 'hw-1000-q7'),
        ('14', 'hw-1000-q8'),
        ('15', 'hw-2000-q2'),
        ('16', 'hw-2000-q3'),
        ('17', 'hw-2000-q4'),
        ('18', 'hw-50-n1'),
        ('19', 'hw-50-n2'),
        ('20', 'hw-50-n3'),
        ('21', 'hw-50-n4'),
        ('22', 'va-10'),
        ('23', 'va-100'),
        ('24', 'va-1000')
    ]

    BUG = [
        ('1', 'Дефект продукта'),
        ('2', 'Дефект автостенда'),
        ('3', 'Новый дефект'),
        ('4', 'Доработка автотеста'),
        ('5', 'Возможный дефект продукта'),
    ]

    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control mb-3',
        'placeholder': 'Сценарий',
        'type': 'text'
    }))

    url_report = forms.URLField(widget=forms.TextInput(attrs={
        'class': 'form-control mb-3',
        'placeholder': 'URL сценария',
        'type': 'url'
    }))

    platform_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control mb-3',
        'placeholder': 'Платформа',
        'id': 'id_platform_name',
    }))

    build_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control mb-3',
        'placeholder': 'Сборка',
        'type': 'text'
    }))

    bug = forms.ChoiceField(choices=BUG, widget=forms.Select(attrs={
        'class': 'form-control mb-3',
        'placeholder': 'Вид дефекта',
    }))

    floating_defect = forms.BooleanField(required=False, initial=False, widget=forms.CheckboxInput)

    id_tfs = forms.CharField(required=False, initial=1, widget=forms.TextInput(attrs={
        'class': 'form-control mb-3',
        'placeholder': 'Id TFS',
    }))

    problem = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control mb-3',
        'placeholder': 'Проблема',
        'type': 'text'
    }))

    my_solution = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control mb-3',
        'placeholder': 'Мое решение',
        'type': 'text'
    }))

    class Meta:
        model = Report
        fields = ('name',
                  'url_report',
                  'platform_name',
                  'build_number',
                  'bug',
                  'floating_defect',
                  'id_tfs',
                  'problem',
                  'my_solution')

text_report/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from text_report.forms import ReportForm
from .models import Report


def index_view(request):
    report_form = ReportForm()

    distinct_dates = Report.objects.values('date_create').distinct()

    data_for_template = {}
    for date in distinct_dates:
        date_value = date['date_create']
        reports_for_date = Report.objects.filter(date_create=date_value)
        data_for_template[date_value] = reports_for_date

    return render(
        request,
        'index.html',
        {'form': report_form,
         'data_for_template': data_for_template
         })


def report_view(request):
    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            floating_bug_value = 'floating_bug' in request.POST

            name = request.POST["name"]
            url_report = request.POST["url_report"]
            platform_name = request.POST["platform_name"]
            build_number = request.POST["build_number"]
            bug = request.POST["bug"]
            id_tfs = request.POST["id_tfs"]
            problem = request.POST["problem"]
            my_solution = request.POST["my_solution"]

            new_report = Report(name=name,
                                url_report=url_report,
                                platform_name=platform_name,
                                build_number=build_number,
                                bug=bug,
                                floating_defect=floating_bug_value,
                                id_tfs=id_tfs,
                                problem=problem,
                                my_solution=my_solution)
            new_report.save()
            return HttpResponseRedirect(reverse('index_view'))
    else:
        form = ReportForm()

    return render(request, 'index.html', {'form': form})


def history_view(request):
    reports = Report.objects.all()
    context = {'reports': reports}
    return render(request, 'index.html', context)

text_report/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Отчеты по разбору отчетов</title>

    <!--  bootstrap  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <!--  jquery  -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body class="d-flex flex-column min-vh-100 justify-content-start align-items-center text-center mt-4">
<div>
    <a href="/" class="btn btn-danger btn-lg btn-block btn-width">Назад</a>
</div>
{% if user.is_authenticated %}
    <div class="container">
                {% block form_content %}
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            <form class="text-center" method="post" action="{% url 'text_report' %}">
                            <h1 class="h3 mb-4 font-weight-normal">Создать отчет</h1>
                                {% csrf_token %}
                                {{form.name}}
                                {{form.url_report}}
                                {{form.platform_name}}
                                {{form.build_number}}
                                <div class="text-start">
                                    <p>Плавающий <input type="checkbox" name="floating_bug" value="on"></p>
                                </div>
                                {{form.bug}}
                                {{form.id_tfs}}
                                {{form.problem}}
                                {{form.my_solution}}
                            <button class="btn btn-lg btn-primary btn-block h3" type="submit" value="Создать">Создать</button>
                            </form>
                        </div>
                    </div>
                {% endblock %}
            </div>
            <div class="col-md-6">
                {% block history_content %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-md-8 justify-content-start">
                                <h1 class="h3 mt-3 font-weight-normal">История отчетов</h1>
                                    <ul  style="text-align: left">
                                        {% for date, reports_for_date in data_for_template.items %}
                                            <p class="card-text">Дата: <span class="badge bg-primary">{{ date }}</span></p>
                                            {% for report in reports_for_date  %}
                                            <li>
                                                [<a href="{{ report.url_report }}" target="_blank">{{ report.name }}</a>]
                                                [{{ report.get_platform_name_display }}]
                                                [{{ report.build_number }}]
                                                [{{report.get_bug_display}}]
                                                {% if report.floating_defect == 1 %}
                                                [Плавающий]
                                                {% endif %}
                                                {% if report.id_tfs > 1000 %}
                                                [#{{report.id_tfs}}]
                                                {% endif %}
                                                <br>
                                                {% if report.problem %}
                                                Проблема: {{ report.problem }}
                                                {% endif %}
                                                <br>
                                                {% if report.my_solution %}
                                                Решение: {{ report.my_solution }}
                                                {% endif %}
                                            </li>
                                                <br>
                                            {% endfor %}
                                        {% endfor %}
                                </ul>
                            </div>
                        </div>
                </div>
                {% endblock %}
            </div>
    </div>
{% endif %}

<script>
    $(function() {
        const platforms = [
          'hw-10-f1', 'hw-100-n1', 'hw-100-n2', 'hw-100-n3', 'hw-100-x3',
          'hw-100-x8', 'hw-1000-q1', 'hw-1000-q2', 'hw-1000-q3', 'hw-1000-q4',
          'hw-1000-q5', 'hw-1000-q6', 'hw-1000-q7', 'hw-1000-q8', 'hw-2000-q2',
          'hw-2000-q3', 'hw-2000-q4', 'hw-50-n1', 'hw-50-n2', 'hw-50-n3',
          'hw-50-n4', 'va-10', 'va-100', 'va-1000'
        ];

        $("#id_platform_name").autocomplete({
          source: platforms
        });
    });
</script>

</body>
</html>